repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-symlinks
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-ast
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
# - repo: https://github.com/pycqa/isort
#   rev: 5.12.0
#   hooks:
#   - id: isort
